# WEATHERMAN DASHBOARD
# For Home Assistant and ESPHome
# Designed by Madelena Mak 2022 - https://mmak.es

# Cue "Blame it on the Weatherman" by B*Witched!
esphome:
  name: "weatherman"
  on_boot:
      priority: 200.0
      then:
        - component.update: eink_display
        - wait_until:
            condition:
              lambda: 'return id(data_updated) == true;'
              # Wait a bit longer so all the items are received
        - delay: 5s
        - logger.log: "Initial sensor data received: Refreshing display..."
        - lambda: 'id(initial_data_received) = true;'
        - script.execute: update_screen

external_components:
  - source: 
      type: local
      path: custom_components/
    components: [ waveshare_7in5h ]

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
#  level: VERBOSE
# Enable Home Assistant API
api:

ota:
  platform: esphome

button:
  - platform: shutdown
    name: "Weatherman - Shutdown"
  - platform: restart
    name: "Weatherman - Restart"
  - platform: template
    name: "Weatherman - Refresh Screen"
    entity_category: config
    on_press:
      - script.execute: update_screen

# Global variables for detecting if the display needs to be refreshed. (Thanks @paviro!)
globals:
  - id: data_updated
    type: bool
    restore_value: no
    initial_value: 'false'
  - id: initial_data_received
    type: bool
    restore_value: no
    initial_value: 'false'
  - id: recorded_display_refresh
    type: int
    restore_value: yes
    initial_value: '0'


# Script for updating screen - Refresh display and publish refresh count and time. (Thanks @paviro!)
script:
  - id: update_screen
    then:
      - lambda: 'id(data_updated) = false;'
      - component.update: eink_display
      - lambda: 'id(recorded_display_refresh) += 1;'      

# Check whether the display needs to be refreshed every minute,
# based on whether new data is received or motion is detected. (Thanks @paviro!)
time:
  - platform: homeassistant
    id: homeassistant_time
    on_time:
      - seconds: 0
        minutes: /10
        then:
          - if:
              condition:
                lambda: 'return id(data_updated) == true;'
              then:
                - logger.log: "Sensor data updated and activity in home detected: Refreshing display..."
                - script.execute: update_screen              
              else:
                - logger.log: "No sensors updated - skipping display refresh."

sensor:
  # Create sensors for monitoring Weatherman remotely.
  - platform: template
    name: "Weatherman - Display Last Update"
    device_class: timestamp
    entity_category: "diagnostic"
    id: display_last_update
    
  - platform: template
    name: "Weatherman - Recorded Display Refresh"
    accuracy_decimals: 0
    unit_of_measurement: "Refreshes"
    state_class: "total_increasing"
    entity_category: "diagnostic"
    lambda: 'return id(recorded_display_refresh);'
  
  - platform: wifi_signal
    name: "Weatherman - WiFi Signal Strength"
    id: wifisignal
    unit_of_measurement: "dBm"
    entity_category: "diagnostic"
    update_interval: 60s

  - platform: homeassistant
    entity_id: sensor.weatherman_data
    attribute: weather_temperature_now
    id: weather_temperature
    on_value:
      then:
        - lambda: 'id(data_updated) = true;'

  - platform: homeassistant
    entity_id: sensor.weatherman_data
    attribute: weather_temperature_0
    id: weather_temperature_0
    on_value:
      then:
        - lambda: 'id(data_updated) = true;'

  - platform: homeassistant
    entity_id: sensor.weatherman_data
    attribute: weather_temperature_1
    id: weather_temperature_1
    on_value:
      then:
        - lambda: 'id(data_updated) = true;'

  - platform: homeassistant
    entity_id: sensor.weatherman_data
    attribute: weather_temperature_2
    id: weather_temperature_2
    on_value:
      then:
        - lambda: 'id(data_updated) = true;'

  - platform: homeassistant
    entity_id: sensor.weatherman_data
    attribute: weather_temperature_3
    id: weather_temperature_3
    on_value:
      then:
        - lambda: 'id(data_updated) = true;'

# Wifi information
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

text_sensor:
  - platform: homeassistant
    entity_id: weather.home
    id: weather_state
    on_value:
      then:
        - lambda: 'id(data_updated) = true;'

  - platform: homeassistant
    entity_id: sensor.weatherman_data
    attribute: weather_condition_now
    id: weather_condition_now
    on_value:
      then:
        - lambda: 'id(data_updated) = true;'
  - platform: homeassistant
    entity_id: sensor.weatherman_data
    attribute: weather_condition_0
    id: weather_condition_0
    on_value:
      then:
        - lambda: 'id(data_updated) = true;'
  - platform: homeassistant
    entity_id: sensor.weatherman_data
    attribute: weather_timestamp_0
    id: weather_timestamp_0
    on_value:
      then:
        - lambda: 'id(data_updated) = true;'
  - platform: homeassistant
    entity_id: sensor.weatherman_data
    attribute: weather_condition_1
    id: weather_condition_1
    on_value:
      then:
        - lambda: 'id(data_updated) = true;'
  - platform: homeassistant
    entity_id: sensor.weatherman_data
    attribute: weather_timestamp_1
    id: weather_timestamp_1
    on_value:
      then:
        - lambda: 'id(data_updated) = true;'
  - platform: homeassistant
    entity_id: sensor.weatherman_data
    attribute: weather_condition_2
    id: weather_condition_2
    on_value:
      then:
        - lambda: 'id(data_updated) = true;'
  - platform: homeassistant
    entity_id: sensor.weatherman_data
    attribute: weather_timestamp_2
    id: weather_timestamp_2
    on_value:
      then:
        - lambda: 'id(data_updated) = true;'
  - platform: homeassistant
    entity_id: sensor.weatherman_data
    attribute: weather_condition_3
    id: weather_condition_3
    on_value:
      then:
        - lambda: 'id(data_updated) = true;'
  - platform: homeassistant
    entity_id: sensor.weatherman_data
    attribute: weather_timestamp_3
    id: weather_timestamp_3
    on_value:
      then:
        - lambda: 'id(data_updated) = true;'

  - platform: homeassistant
    entity_id: sensor.weatherman_data
    attribute: calendar_summary_0
    id: calendar_summary_0
  - platform: homeassistant
    entity_id: sensor.weatherman_data
    attribute: calendar_month_0
    id: calendar_month_0
  - platform: homeassistant
    entity_id: sensor.weatherman_data
    attribute: calendar_day_0
    id: calendar_day_0
  - platform: homeassistant
    entity_id: sensor.weatherman_data
    attribute: calendar_summary_1
    id: calendar_summary_1
  - platform: homeassistant
    entity_id: sensor.weatherman_data
    attribute: calendar_month_1
    id: calendar_month_1
  - platform: homeassistant
    entity_id: sensor.weatherman_data
    attribute: calendar_day_1
    id: calendar_day_1
  - platform: homeassistant
    entity_id: sensor.weatherman_data
    attribute: calendar_summary_2
    id: calendar_summary_2
  - platform: homeassistant
    entity_id: sensor.weatherman_data
    attribute: calendar_month_2
    id: calendar_month_2
  - platform: homeassistant
    entity_id: sensor.weatherman_data
    attribute: calendar_day_2
    id: calendar_day_2

# Define colors
# This design is white on black so this is necessary.
color:
  - id: color_black
    red: 0%
    green: 0%
    blue: 0%
  - id: color_white
    red: 100%
    green: 100%
    blue: 100%
  - id: color_red
    red: 100%
    green: 0%
    blue: 0%
  - id: color_yellow
    red: 100%
    green: 100%
    blue: 0%


# Pins for Waveshare ePaper ESP Board
spi:
  clk_pin: GPIO13
  mosi_pin: GPIO14


# Include custom fonts
font:
  - file: 'fonts/GothamRnd-Book.ttf'
    id: font_small_book
    size: 20
  - file: 'fonts/GothamRnd-Bold.ttf'
    id: font_large_bold
    size: 108
    glyphs: [' ', '-', '°', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'C', 'F']
  - file: 'fonts/GothamRnd-Bold.ttf'
    id: font_title
    size: 54
    glyphs: ['W', 'E', 'A', 'T', 'H', 'R', 'L', 'I', 'N', ' ']
  - file: 'fonts/GothamRnd-Bold.ttf'
    id: font_medium_bold
    size: 30
    # glyphs: [' ', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'M', 'I', 'N']
  - file: 'fonts/GothamRnd-Bold.ttf'
    id: font_small_bold
    size: 18
    # glyphs: [' ', '-', '°', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'C', 'M', 'I', 'N']
  - file: "gfonts://Google Sans"
    id: font_tiny
    size: 16

  # Include Material Design Icons font
  # Thanks to https://community.home-assistant.io/t/display-materialdesign-icons-on-esphome-attached-to-screen/199790/16
  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: font_mdi_large
    size: 96
    glyphs: &mdi-weather-glyphs
      - "\U000F0590" # mdi-weather-cloudy
      - "\U000F0F2F" # mdi-weather-cloudy-alert
      - "\U000F0E6E" # mdi-weather-cloudy-arrow-right
      - "\U000F0591" # mdi-weather-fog
      - "\U000F0592" # mdi-weather-hail
      - "\U000F0F30" # mdi-weather-hazy
      - "\U000F0898" # mdi-weather-hurricane
      - "\U000F0593" # mdi-weather-lightning
      - "\U000F067E" # mdi-weather-lightning-rainy
      - "\U000F0594" # mdi-weather-night
      - "\U000F0F31" # mdi-weather-night-partly-cloudy
      - "\U000F0595" # mdi-weather-partly-cloudy
      - "\U000F0F32" # mdi-weather-partly-lightning
      - "\U000F0F33" # mdi-weather-partly-rainy
      - "\U000F0F34" # mdi-weather-partly-snowy
      - "\U000F0F35" # mdi-weather-partly-snowy-rainy
      - "\U000F0596" # mdi-weather-pouring
      - "\U000F0597" # mdi-weather-rainy
      - "\U000F0598" # mdi-weather-snowy
      - "\U000F0F36" # mdi-weather-snowy-heavy
      - "\U000F067F" # mdi-weather-snowy-rainy
      - "\U000F0599" # mdi-weather-sunny
      - "\U000F0F37" # mdi-weather-sunny-alert
      - "\U000F14E4" # mdi-weather-sunny-off
      - "\U000F059A" # mdi-weather-sunset
      - "\U000F059B" # mdi-weather-sunset-down
      - "\U000F059C" # mdi-weather-sunset-up
      - "\U000F0F38" # mdi-weather-tornado
      - "\U000F059D" # mdi-weather-windy
      - "\U000F059E" # mdi-weather-windy-variant
      - "\U000F00ED" # mdi-calendar
  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: font_mdi_medium
    size: 36
    glyphs: *mdi-weather-glyphs

# Now render everything on the ePaper screen.
display:
  - platform: waveshare_7in5h
    id: eink_display
    model: "7.5in-h"
    cs_pin: GPIO15
    dc_pin: GPIO27
    busy_pin: GPIO25
    reset_pin: GPIO26
    reset_duration: 5ms
    update_interval: never
    rotation: 270°
    lambda: |-
      // Fill background.
      it.fill(id(color_white));
      
      // Map weather states to MDI characters.
      std::map<std::string, std::string> weather_icon_map
        {
          {"cloudy", "\U000F0590"},
          {"cloudy-alert", "\U000F0F2F"},
          {"cloudy-arrow-right", "\U000F0E6E"},
          {"fog", "\U000F0591"},
          {"hail", "\U000F0592"},
          {"hazy", "\U000F0F30"},
          {"hurricane", "\U000F0898"},
          {"lightning", "\U000F0593"},
          {"lightning-rainy", "\U000F067E"},
          {"clear-night", "\U000F0594"},
          {"night-partly-cloudy", "\U000F0F31"},
          {"partlycloudy", "\U000F0595"},
          {"partly-lightning", "\U000F0F32"},
          {"partly-rainy", "\U000F0F33"},
          {"partly-snowy", "\U000F0F34"},
          {"partly-snowy-rainy", "\U000F0F35"},
          {"pouring", "\U000F0596"},
          {"rainy", "\U000F0597"},
          {"snowy", "\U000F0598"},
          {"snowy-heavy", "\U000F0F36"},
          {"snowy-rainy", "\U000F067F"},
          {"sunny", "\U000F0599"},
          {"sunny-alert", "\U000F0F37"},
          {"sunny-off", "\U000F14E4"},
          {"sunset", "\U000F059A"},
          {"sunset-down", "\U000F059B"},
          {"sunset-up", "\U000F059C"},
          {"tornado", "\U000F0F38"},
          {"windy", "\U000F059D"},
          {"windy-variant", "\U000F059E"},
        };
        // Weather Section
        // it.image(0, 88, id(title_weather)); 
        it.printf(220, 84, id(font_title), color_black, TextAlign::TOP_CENTER, "WEATHER");
        it.strftime(220, 138, id(font_small_book), color_black, TextAlign::TOP_CENTER, "%A, %B %e", id(homeassistant_time).now());
        
        it.printf(90, 180, id(font_mdi_large), color_black, TextAlign::TOP_CENTER, "%s", weather_icon_map[id(weather_condition_now).state.c_str()].c_str());
        it.printf(280, 180, id(font_large_bold), color_black, TextAlign::TOP_CENTER, "%2.0f°F", id(weather_temperature).state);

        int x_pos_forecast_start = 100;
        int x_pos_spacing = 130;
        int y_pos_forecast = 320;
        it.printf(x_pos_forecast_start, y_pos_forecast, id(font_small_book), color_black, TextAlign::TOP_CENTER, "%s", id(weather_timestamp_0).state.c_str());
        it.printf(x_pos_forecast_start, y_pos_forecast + 24, id(font_mdi_medium), color_black, TextAlign::TOP_CENTER, "%s", weather_icon_map[id(weather_condition_0).state.c_str()].c_str());
        it.printf(x_pos_forecast_start, y_pos_forecast + 72, id(font_small_bold), color_black, TextAlign::TOP_CENTER, "%2.0f°F", id(weather_temperature_0).state);

        it.printf(x_pos_forecast_start + x_pos_spacing, y_pos_forecast, id(font_small_book), color_black, TextAlign::TOP_CENTER, "%s", id(weather_timestamp_1).state.c_str());
        it.printf(x_pos_forecast_start + x_pos_spacing, y_pos_forecast + 24, id(font_mdi_medium), color_black, TextAlign::TOP_CENTER, "%s", weather_icon_map[id(weather_condition_1).state.c_str()].c_str());
        it.printf(x_pos_forecast_start + x_pos_spacing, y_pos_forecast + 72, id(font_small_bold), color_black, TextAlign::TOP_CENTER, "%2.0f°F", id(weather_temperature_1).state);

        it.printf(x_pos_forecast_start + 2 * x_pos_spacing, y_pos_forecast, id(font_small_book), color_black, TextAlign::TOP_CENTER, "%s", id(weather_timestamp_2).state.c_str());
        it.printf(x_pos_forecast_start + 2 * x_pos_spacing, y_pos_forecast + 24, id(font_mdi_medium), color_black, TextAlign::TOP_CENTER, "%s", weather_icon_map[id(weather_condition_2).state.c_str()].c_str());
        it.printf(x_pos_forecast_start + 2 * x_pos_spacing, y_pos_forecast + 72, id(font_small_bold), color_black, TextAlign::TOP_CENTER, "%2.0f°F", id(weather_temperature_2).state);

        // Calendar Section
        it.line(20, 460, 420, 460, color_black); // Divider line
        int start_y_calendar = 480;
        int x_pos_date = 50;
        int x_pos_summary = 110;
        int row_height = 60; // Vertical distance between the start of each event

        // Print the main calendar icon header
        it.printf(x_pos_date + 110, start_y_calendar, font_mdi_medium, color_black, TextAlign::TOP_CENTER, "\U000F00ED");
        it.printf(x_pos_date + 210, start_y_calendar + 10, font_small_bold, color_black, TextAlign::TOP_CENTER, "NEXT EVENTS");

        int current_y = start_y_calendar + 70; // Start Y for the first event

        // --- Event 1: Trash Pickup (Example from your data) ---
        // This logic would be inside a loop over your actual calendar sensor events
        it.printf(x_pos_date, current_y, font_tiny, color_black, TextAlign::TOP_LEFT, "%s", id(calendar_month_0).state.c_str());
        it.printf(x_pos_date+5, current_y + 22, font_tiny, color_black, TextAlign::TOP_LEFT, "%s", id(calendar_day_0).state.c_str());
        it.printf(x_pos_summary, current_y + 8, font_small_book, color_black, TextAlign::TOP_LEFT, "%s", id(calendar_summary_0).state.c_str());

        current_y += row_height; // Move to next row's Y position

        // --- Event 2: Browning road Block party (Example from your data) ---
        it.printf(x_pos_date, current_y, font_tiny, color_black, TextAlign::TOP_LEFT, "%s", id(calendar_month_1).state.c_str());
        it.printf(x_pos_date+5, current_y + 22, font_tiny, color_black, TextAlign::TOP_LEFT, "%s", id(calendar_day_1).state.c_str());
        it.printf(x_pos_summary, current_y + 8, font_small_book, color_black, TextAlign::TOP_LEFT, "%s", id(calendar_summary_1).state.c_str());

        current_y += row_height; // Move to next row's Y position
        
        // --- Event 3: Sophia Bath Time (Example from your data) ---
        it.printf(x_pos_date, current_y, font_tiny, color_black, TextAlign::TOP_LEFT, "%s", id(calendar_month_2).state.c_str());
        it.printf(x_pos_date+5, current_y + 22, font_tiny, color_black, TextAlign::TOP_LEFT, "%s", id(calendar_day_2).state.c_str());
        it.printf(x_pos_summary, current_y + 8, font_small_book, color_black, TextAlign::TOP_LEFT, "%s", id(calendar_summary_2).state.c_str());

        // Refresh Timestamp
        // Code by EnsconcE from https://community.home-assistant.io/t/esphome-show-time/348903
        char str[17];
        time_t currTime = id(homeassistant_time).now().timestamp;
        strftime(str, sizeof(str), "%H:%M", localtime(&currTime));
        it.printf(240, 710, id(font_small_book), color_black, TextAlign::TOP_CENTER, "REFRESHED AT %s", str);
      
